# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'MarvelUniverse' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MarvelUniverse
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Messaging', '~> 5.3.0'
  target 'MarvelUniverse-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarvelUniverseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MarvelUniverse-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MarvelUniverse-tvOS


end
