# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'platziApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for platziApp
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Messaging', '~> 5.3.0'
  target 'platziApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'platziAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'platziApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for platziApp-tvOS


end
